version: "2"
services:
  namenode:
    image: apache/hadoop:${HADOOP_VERSION}
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
      - 8020:8020
    env_file:
      - ./config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
  datanode:
    image: apache/hadoop:${HADOOP_VERSION}
    command: ["hdfs", "datanode"]
    env_file:
      - ./config
    ports:
      - 9867:9867
  resourcemanager:
    image: apache/hadoop:${HADOOP_VERSION}
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088
    env_file:
      - ./config
    volumes:
      - ./test.sh:/opt/test.sh
  nodemanager:
    image: apache/hadoop:${HADOOP_VERSION}
    command: ["yarn", "nodemanager"]
    env_file:
      - ./config
    ports:
      - 8040:8040